//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class AccessTokenRequest
    {

        /// <summary>
        /// The access token associated with the Item data is being requested for
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; set; } = default!;
    }
}