//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum AccountSelectModeEnum
    {
        [JsonProperty("All")]
        All,
        [JsonProperty("Single")]
        Single,
        [JsonProperty("Multiple")]
        Multiple,
    }

    public static class AccountSelectModeEnumExtension
    {
        public static string Value(this AccountSelectModeEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccountSelectModeEnum ToEnum(this string value)
        {
            foreach(var field in typeof(AccountSelectModeEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccountSelectModeEnum)
                    {
                        return (AccountSelectModeEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccountSelectModeEnum");
        }
    }

}