//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class ConnectionPublicTokenExchangeRequest
    {

        /// <summary>
        /// Your public_token, obtained from the Link onSuccess callback
        /// </summary>
        [JsonProperty("public_token")]
        public string PublicToken { get; set; } = default!;
    }
}