//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class ConnectionPublicTokenExchangeResponse
    {

        /// <summary>
        /// The access token associated with the connection data is being requested for
        /// </summary>
        [JsonProperty("access_token")]
        public string? AccessToken { get; set; }

        /// <summary>
        /// The Deck Connection ID for the connection associated with the returned access token
        /// </summary>
        [JsonProperty("connection_id")]
        public string? ConnectionId { get; set; }

        /// <summary>
        /// List of non-sensitive values provided from the Link session by the user
        /// </summary>
        [JsonProperty("fields")]
        public List<LinkConnectRequestField> Fields { get; set; } = default!;
    }
}