//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class ConnectionContextResponse
    {

        /// <summary>
        /// The Deck Connection ID associated with the access token data being requested
        /// </summary>
        [JsonProperty("connection_id")]
        public string? ConnectionId { get; set; }

        /// <summary>
        /// The data source associated to this connectiond
        /// </summary>
        [JsonProperty("provider")]
        public Provider Provider { get; set; } = default!;

        /// <summary>
        /// Represents the current connection health status between the system and the data source, such as Connected or Disconnected.
        /// </summary>
        [JsonProperty("connection_status")]
        public ConnectivityStatusEnum? ConnectionStatus { get; set; }

        /// <summary>
        /// The UTC timestamp of when the connectivity status was last updated.
        /// </summary>
        [JsonProperty("connection_status_timestamp")]
        public DateTime? ConnectionStatusTimestamp { get; set; }

        /// <summary>
        /// Represents the most recent scraping result for this connection, providing additional context to the connectivity status.
        /// </summary>
        [JsonProperty("connection_status_reason")]
        public ScrapingStatusEnum? ConnectionStatusReason { get; set; }

        /// <summary>
        /// Represents the number of accounts.
        /// </summary>
        [JsonProperty("num_of_entities")]
        public int? NumOfEntities { get; set; }

        /// <summary>
        /// A list of entities associated with this connection.
        /// </summary>
        [JsonProperty("entities")]
        public List<Entity> Entities { get; set; } = default!;
    }
}