//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public class DocumentInfo
    {

        [JsonProperty("document_id")]
        public string DocumentId { get; set; } = default!;

        [JsonProperty("file_type")]
        public string FileType { get; set; } = default!;

        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        [JsonProperty("file_name")]
        public string? FileName { get; set; } = null;

        [JsonProperty("file_size")]
        public long? FileSize { get; set; } = null;

        [JsonProperty("fetch_date")]
        public DateTime? FetchDate { get; set; }
    }
}