//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum ErrorCategoryEnum
    {
        [JsonProperty("INVALID_REQUEST")]
        InvalidRequest,
        [JsonProperty("INVALID_RESULT")]
        InvalidResult,
        [JsonProperty("INVALID_INPUT")]
        InvalidInput,
        [JsonProperty("DATA_SOURCE_ERROR")]
        DataSourceError,
        [JsonProperty("RATE_LIMIT_EXCEEDED")]
        RateLimitExceeded,
        [JsonProperty("API_ERROR")]
        ApiError,
        [JsonProperty("CONNECTION_ERROR")]
        ConnectionError,
        [JsonProperty("RECAPTCHA_ERROR")]
        RecaptchaError,
        [JsonProperty("FETCH_BALANCE")]
        FetchBalance,
        [JsonProperty("ADD_PAYMENT_METHOD")]
        AddPaymentMethod,
        [JsonProperty("FETCH_PAYMENT_METHODS")]
        FetchPaymentMethods,
        [JsonProperty("PAYMENT")]
        Payment,
    }

    public static class ErrorCategoryEnumExtension
    {
        public static string Value(this ErrorCategoryEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ErrorCategoryEnum ToEnum(this string value)
        {
            foreach(var field in typeof(ErrorCategoryEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ErrorCategoryEnum)
                    {
                        return (ErrorCategoryEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ErrorCategoryEnum");
        }
    }

}