//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum FieldTypeEnum
    {
        [JsonProperty("Text")]
        Text,
        [JsonProperty("Password")]
        Password,
    }

    public static class FieldTypeEnumExtension
    {
        public static string Value(this FieldTypeEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static FieldTypeEnum ToEnum(this string value)
        {
            foreach(var field in typeof(FieldTypeEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is FieldTypeEnum)
                    {
                        return (FieldTypeEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum FieldTypeEnum");
        }
    }

}