//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class GetConnectionAccountsResponseAccount
    {

        [JsonProperty("account_number")]
        public string AccountNumber { get; set; } = default!;

        [JsonProperty("is_selected")]
        public bool IsSelected { get; set; } = default!;
    }
}