//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class JobResponse
    {

        /// <summary>
        /// The unique identifier of the job.
        /// </summary>
        [JsonProperty("job_guid")]
        public string JobGuid { get; set; } = default!;

        /// <summary>
        /// The code representing the type of job executed.
        /// </summary>
        [JsonProperty("job_code")]
        public string JobCode { get; set; } = default!;
    }
}