//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class LinkConnectRequest
    {

        /// <summary>
        /// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
        /// </summary>
        [JsonProperty("link_token")]
        public string LinkToken { get; set; } = default!;

        /// <summary>
        /// Identifier of the data source to connect to.
        /// </summary>
        [JsonProperty("source_id")]
        public string SourceId { get; set; } = default!;

        /// <summary>
        /// List of values provided for fields specific to the selected source
        /// </summary>
        [JsonProperty("fields")]
        public List<LinkConnectRequestField> Fields { get; set; } = default!;

        /// <summary>
        /// The accepted terms of use by the end-user
        /// </summary>
        [JsonProperty("terms_of_use_url")]
        public string? TermsOfUseUrl { get; set; } = null;

        /// <summary>
        /// The accepted privacy policy by the end-user
        /// </summary>
        [JsonProperty("privacy_policy_url")]
        public string? PrivacyPolicyUrl { get; set; } = null;
    }
}