//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class LinkAccountListResponse
    {

        /// <summary>
        /// List of available accounts
        /// </summary>
        [JsonProperty("accounts")]
        public List<LinkAccountListResponseAccountItem>? Accounts { get; set; }
    }
}