//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class LinkSourcesRequest
    {

        /// <summary>
        /// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
        /// </summary>
        [JsonProperty("link_token")]
        public string LinkToken { get; set; } = default!;

        /// <summary>
        /// The specific source identifier to find. If left to NULL, a list of the 15 most common data sources is returned. If specified, the search argument will be ignored.
        /// </summary>
        [JsonProperty("source_id")]
        public string? SourceId { get; set; } = null;

        /// <summary>
        /// A search term for filtering the list by data source name. If left to NULL or empty, a list of the 15 most common data sources is returned.
        /// </summary>
        [JsonProperty("search")]
        public string? Search { get; set; } = null;
    }
}