//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class LinkTokenGetResponse
    {

        /// <summary>
        /// The language used for the Link session corresponding to the provided Link token
        /// </summary>
        [JsonProperty("language")]
        public LinkTokenGetResponseLanguage? Language { get; set; } = null;

        /// <summary>
        /// The beta source status filter from which data sources will be displayed during the Link session corresponding to the provided Link token.
        /// </summary>
        [JsonProperty("beta_source_status")]
        public LinkTokenGetResponseBetaSourceStatus? BetaSourceStatus { get; set; } = null;

        /// <summary>
        /// The countries filter from which data sources will be displayed during the Link session corresponding to the provided Link token
        /// </summary>
        [JsonProperty("countries")]
        public List<string>? Countries { get; set; } = null;

        /// <summary>
        /// The source types filter from which data sources will be displayed during the Link session corresponding to the provided Link token
        /// </summary>
        [JsonProperty("source_types")]
        public List<string>? SourceTypes { get; set; } = null;

        [JsonProperty("source_guids")]
        public List<string>? SourceGuids { get; set; } = null;
    }
}