//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The language that Link should be displayed in.
    /// </summary>
    public enum LinkTokenCreateRequestLanguage
    {
        [JsonProperty("EN")]
        En,
        [JsonProperty("ES")]
        Es,
        [JsonProperty("FR")]
        Fr,
        [JsonProperty("DE")]
        De,
        [JsonProperty("IT")]
        It,
        [JsonProperty("PT")]
        Pt,
        [JsonProperty("NL")]
        Nl,
        [JsonProperty("PL")]
        Pl,
        [JsonProperty("SV")]
        Sv,
        [JsonProperty("DA")]
        Da,
        [JsonProperty("NO")]
        No,
        [JsonProperty("ET")]
        Et,
        [JsonProperty("LT")]
        Lt,
        [JsonProperty("LV")]
        Lv,
        [JsonProperty("RO")]
        Ro,
    }

    public static class LinkTokenCreateRequestLanguageExtension
    {
        public static string Value(this LinkTokenCreateRequestLanguage value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LinkTokenCreateRequestLanguage ToEnum(this string value)
        {
            foreach(var field in typeof(LinkTokenCreateRequestLanguage).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LinkTokenCreateRequestLanguage)
                    {
                        return (LinkTokenCreateRequestLanguage)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LinkTokenCreateRequestLanguage");
        }
    }

}