//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class LinkTokenRequestResponse
    {

        /// <summary>
        /// The link_token, must be provided when calling Link endpoints, for identifying the Link session.
        /// </summary>
        [JsonProperty("link_token")]
        public string LinkToken { get; set; } = default!;
    }
}