//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class LinkSourcesResponseSource
    {

        /// <summary>
        /// Unique identifier of the source with Datadeck.
        /// </summary>
        [JsonProperty("source_id")]
        public string? SourceId { get; set; }

        /// <summary>
        /// Name of the data source.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Url to display the data source logo, when available (can be null).
        /// </summary>
        [JsonProperty("logo_url")]
        public string? LogoUrl { get; set; } = null;

        /// <summary>
        /// Country code of the data source in ISO 3166 format (2 characters).
        /// </summary>
        [JsonProperty("country")]
        public string? Country { get; set; } = null;

        /// <summary>
        /// Website of the data source, useful for resetting a password.
        /// </summary>
        [JsonProperty("website")]
        public string? Website { get; set; } = null;

        /// <summary>
        /// The required fields to be displayed to the user for entering his credentials. In Update mode (for changing a password), the Username value of the connection being updated will also be provided, to be displayed in read-only.
        /// </summary>
        [JsonProperty("fields")]
        public List<LinkSourcesResponseSourceField>? Fields { get; set; }
    }
}