//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class LinkTokenCreateRequest
    {

        /// <summary>
        /// The language that Link should be displayed in.
        /// </summary>
        [JsonProperty("language")]
        public LinkTokenCreateRequestLanguage? Language { get; set; } = null;

        /// <summary>
        /// Specify an array of Datadeck-supported country codes using the ISO-3166-1 alpha-2 country code standard. Sources from all listed countries will be shown.
        /// </summary>
        [JsonProperty("countries")]
        public List<string>? Countries { get; set; } = null;

        /// <summary>
        /// You can specify exactly the sources to be shown in Link by providing a list of source ids.
        /// </summary>
        [JsonProperty("source_ids")]
        public List<string>? SourceIds { get; set; } = null;

        /// <summary>
        /// You can limit the sources to be shown in Link by specifying which source types to be shown in Link.
        /// </summary>
        [JsonProperty("source_types")]
        public List<string>? SourceTypes { get; set; } = null;

        /// <summary>
        /// To control which sources to be shown regarding their beta status
        /// </summary>
        [JsonProperty("beta_source_status")]
        public LinkTokenCreateRequestBetaSourceStatus? BetaSourceStatus { get; set; } = null;

        /// <summary>
        /// Used for launching Link in update or refresh mode
        /// </summary>
        [JsonProperty("update")]
        public Update? Update { get; set; } = null;

        /// <summary>
        /// The webhook URL to receive update events.
        /// </summary>
        [JsonProperty("webhook_url")]
        public string? WebhookUrl { get; set; } = null;

        /// <summary>
        /// If true, the Link session will automatically refresh the data.
        /// </summary>
        [JsonProperty("auto_refresh")]
        public bool? AutoRefresh { get; set; } = null;

        /// <summary>
        /// Choose the type of parsing needed for the connection
        /// </summary>
        [JsonProperty("parsing_method")]
        public ParsingMethod? ParsingMethod { get; set; } = null;

        /// <summary>
        /// Specifies whether to collect only the latest invoice data or all available invoices
        /// </summary>
        [JsonProperty("latest_invoice_only")]
        public bool? LatestInvoiceOnly { get; set; } = null;
    }
}