//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class LinkSourcesResponseSourceField
    {

        [JsonProperty("field_number")]
        public int FieldNumber { get; set; } = default!;

        [JsonProperty("field_name")]
        public string FieldName { get; set; } = default!;

        [JsonProperty("field_label")]
        public string FieldLabel { get; set; } = default!;

        [JsonProperty("field_value")]
        public string? FieldValue { get; set; } = null;

        [JsonProperty("field_type")]
        public FieldTypeEnum? FieldType { get; set; }
    }
}