//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum LinkTokenCreateRequestUpdateModeEnum
    {
        [JsonProperty("UpdateCredentials")]
        UpdateCredentials,
        [JsonProperty("Refresh")]
        Refresh,
        [JsonProperty("UpdateAccountSelection")]
        UpdateAccountSelection,
    }

    public static class LinkTokenCreateRequestUpdateModeEnumExtension
    {
        public static string Value(this LinkTokenCreateRequestUpdateModeEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LinkTokenCreateRequestUpdateModeEnum ToEnum(this string value)
        {
            foreach(var field in typeof(LinkTokenCreateRequestUpdateModeEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LinkTokenCreateRequestUpdateModeEnum)
                    {
                        return (LinkTokenCreateRequestUpdateModeEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LinkTokenCreateRequestUpdateModeEnum");
        }
    }

}