//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The beta source status filter from which data sources will be displayed during the Link session corresponding to the provided Link token.
    /// </summary>
    public enum LinkTokenGetResponseBetaSourceStatus
    {
        [JsonProperty("LiveAndBeta")]
        LiveAndBeta,
        [JsonProperty("OnlyLive")]
        OnlyLive,
        [JsonProperty("OnlyBeta")]
        OnlyBeta,
    }

    public static class LinkTokenGetResponseBetaSourceStatusExtension
    {
        public static string Value(this LinkTokenGetResponseBetaSourceStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LinkTokenGetResponseBetaSourceStatus ToEnum(this string value)
        {
            foreach(var field in typeof(LinkTokenGetResponseBetaSourceStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LinkTokenGetResponseBetaSourceStatus)
                    {
                        return (LinkTokenGetResponseBetaSourceStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LinkTokenGetResponseBetaSourceStatus");
        }
    }

}