//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class LinkAccountListResponseAccountItem
    {

        /// <summary>
        /// The account identifier
        /// </summary>
        [JsonProperty("account_id")]
        public string? AccountId { get; set; }

        [JsonProperty("account_number")]
        public string? AccountNumber { get; set; }

        /// <summary>
        /// The account&apos;s address if available
        /// </summary>
        [JsonProperty("account_address")]
        public string? AccountAddress { get; set; } = null;
    }
}