//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum LinkConnectionStatusResponseEnum
    {
        [JsonProperty("New")]
        New,
        [JsonProperty("Connecting")]
        Connecting,
        [JsonProperty("Connected")]
        Connected,
        [JsonProperty("InvalidCredentials")]
        InvalidCredentials,
        [JsonProperty("Error")]
        Error,
        [JsonProperty("MfaMethodChoice")]
        MfaMethodChoice,
        [JsonProperty("MfaQuestion")]
        MfaQuestion,
        [JsonProperty("MfaQuestionInvalidAnswer")]
        MfaQuestionInvalidAnswer,
        [JsonProperty("MfaQuestionNoAnswer")]
        MfaQuestionNoAnswer,
        [JsonProperty("Captcha")]
        Captcha,
        [JsonProperty("SecurityQuestion")]
        SecurityQuestion,
        [JsonProperty("AccountSelection")]
        AccountSelection,
    }

    public static class LinkConnectionStatusResponseEnumExtension
    {
        public static string Value(this LinkConnectionStatusResponseEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LinkConnectionStatusResponseEnum ToEnum(this string value)
        {
            foreach(var field in typeof(LinkConnectionStatusResponseEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LinkConnectionStatusResponseEnum)
                    {
                        return (LinkConnectionStatusResponseEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LinkConnectionStatusResponseEnum");
        }
    }

}