//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class LinkConnectionStatusResponse
    {

        /// <summary>
        /// The current status of the connection requested
        /// </summary>
        [JsonProperty("status")]
        public LinkConnectionStatusResponseEnum? Status { get; set; }

        /// <summary>
        /// Additional information related to the status
        /// </summary>
        [JsonProperty("additional_information")]
        public string? AdditionalInformation { get; set; } = null;
    }
}