//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Choose the type of parsing needed for the connection
    /// </summary>
    public enum ParsingMethod
    {
        [JsonProperty("PdfOnly")]
        PdfOnly,
        [JsonProperty("Basic")]
        Basic,
        [JsonProperty("FullSustainability")]
        FullSustainability,
        [JsonProperty("None")]
        None,
    }

    public static class ParsingMethodExtension
    {
        public static string Value(this ParsingMethod value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ParsingMethod ToEnum(this string value)
        {
            foreach(var field in typeof(ParsingMethod).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ParsingMethod)
                    {
                        return (ParsingMethod)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ParsingMethod");
        }
    }

}