//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class Provider
    {

        /// <summary>
        /// Unique identifier of the data provider associated to this connectiond
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Name of the data source provider to this connection
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }
    }
}