//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum ScrapingStatusEnum
    {
        [JsonProperty("New")]
        New,
        [JsonProperty("Connecting")]
        Connecting,
        [JsonProperty("CredentialsSent")]
        CredentialsSent,
        [JsonProperty("InvalidCredentials")]
        InvalidCredentials,
        [JsonProperty("ConnectedCredentials")]
        ConnectedCredentials,
        [JsonProperty("SecurityAnswerRequired")]
        SecurityAnswerRequired,
        [JsonProperty("SecurityAnswerInvalid")]
        SecurityAnswerInvalid,
        [JsonProperty("SecurityQuestionTimeout")]
        SecurityQuestionTimeout,
        [JsonProperty("MfaMethodChoiceRequired")]
        MfaMethodChoiceRequired,
        [JsonProperty("MfaCodeRequired")]
        MfaCodeRequired,
        [JsonProperty("MfaCodeInvalid")]
        MfaCodeInvalid,
        [JsonProperty("MfaCodeTimeout")]
        MfaCodeTimeout,
        [JsonProperty("MfaActionRequired")]
        MfaActionRequired,
        [JsonProperty("BlockedByPin")]
        BlockedByPin,
        [JsonProperty("AccountSelectionRequired")]
        AccountSelectionRequired,
        [JsonProperty("WaitingForJob")]
        WaitingForJob,
        [JsonProperty("ExecutingJob")]
        ExecutingJob,
        [JsonProperty("CompletedJob")]
        CompletedJob,
        [JsonProperty("RetryLater")]
        RetryLater,
        [JsonProperty("DataFound")]
        DataFound,
        [JsonProperty("ConnectedWaitingOnDataExtraction")]
        ConnectedWaitingOnDataExtraction,
        [JsonProperty("NoDataFound")]
        NoDataFound,
        [JsonProperty("NoStatement")]
        NoStatement,
        [JsonProperty("Error")]
        Error,
    }

    public static class ScrapingStatusEnumExtension
    {
        public static string Value(this ScrapingStatusEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ScrapingStatusEnum ToEnum(this string value)
        {
            foreach(var field in typeof(ScrapingStatusEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ScrapingStatusEnum)
                    {
                        return (ScrapingStatusEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ScrapingStatusEnum");
        }
    }

}