//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Utils;
    
    public class Security
    {

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=x-deck-client-id")]
        public string ClientId { get; set; } = default!;

        [SpeakeasyMetadata("security:scheme=true,type=apiKey,subType=header,name=x-deck-secret")]
        public string Secret { get; set; } = default!;
    }
}