//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Used for launching Link in update or refresh mode
    /// </summary>
    public class Update
    {

        /// <summary>
        /// The `access_token` associated with the existing Connection to update
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; set; } = default!;

        /// <summary>
        /// Set which mode you want to use between Update and Refresh.<br/>
        /// 
        /// <remarks>
        /// Update mode will ask to enter the password, for updating it.<br/>
        /// Refresh mode will re-use existing known credentials and will only let the user interact with the MFA step during sign-in.
        /// </remarks>
        /// </summary>
        [JsonProperty("mode")]
        public LinkTokenCreateRequestUpdateModeEnum Mode { get; set; } = default!;
    }
}