//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Components
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Information about the source, if using Link in Update mode.
    /// </summary>
    public class UpdateMode
    {

        /// <summary>
        /// When using Link in Update mode, this contains information about the original data source for which we are updating the connection.
        /// </summary>
        [JsonProperty("source")]
        public LinkSourcesResponseSource Source { get; set; } = default!;
    }
}