//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Errors
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class AlreadyRunningJobResponseException : Exception
    {

        /// <summary>
        /// [Obsolete] Legacy identifier of the job. Use JobGuid instead.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("job_id")]
        public string JobId { get; set; } = default!;

        /// <summary>
        /// Unique identifier of the already running job.
        /// </summary>
        [JsonProperty("job_guid")]
        public string JobGuid { get; set; } = default!;

        /// <summary>
        /// [Obsolete] Legacy message describing the conflict. Use ErrorMessage instead.
        /// </summary>
        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [JsonProperty("message")]
        private string? _message { get; set; }
        public override string Message { get {return _message ?? "";} }

        /// <summary>
        /// A human-readable error message indicating the job is already in progress.
        /// </summary>
        [JsonProperty("error_message")]
        public string ErrorMessage { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }
}