//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Errors
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class ErrorMessageResponse : Exception
    {

        /// <summary>
        /// A broad categorization of the error. Safe for programmatic use.
        /// </summary>
        [JsonProperty("error_category")]
        public ErrorCategoryEnum? ErrorCategory { get; set; }

        /// <summary>
        /// The particular error code. Safe for programmatic use.
        /// </summary>
        [JsonProperty("error_code")]
        public ErrorCodeEnum? ErrorCode { get; set; }

        /// <summary>
        /// A developer-friendly representation of the error code. This may change over time and is not safe for programmatic use.
        /// </summary>
        [JsonProperty("error_message")]
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// A user-friendly representation of the error code. null if the error is not related to user action. This may change over time and is not safe for programmatic use.
        /// </summary>
        [JsonProperty("display_message")]
        public string? DisplayMessage { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }
}