//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Requests
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    
    public class PostJobsDocumentsListRequest
    {

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=job_guid")]
        public string? JobGuid { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public AccessTokenRequest? AccessTokenRequest { get; set; }
    }
}