//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Requests
{
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class PostJobsSubmitRequest
    {

        /// <summary>
        /// The job type identifier
        /// </summary>
        [JsonProperty("job_code")]
        public string JobCode { get; set; } = default!;

        /// <summary>
        /// Dynamic input object - structure varies by job type
        /// </summary>
        [JsonProperty("input")]
        public Dictionary<string, string> Input { get; set; } = default!;
    }
}