//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Deck.SDK.Models.Requests
{
    using Deck.SDK.Models.Components;
    using Deck.SDK.Utils;
    using Newtonsoft.Json;
    
    public class PostLinkTokenGetResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// OK
        /// </summary>
        public LinkTokenGetResponse? LinkTokenGetResponse { get; set; }
    }
}